### ISSUE TITLE
Problems with /xmlquery

### ISSUE THREAD

**Issue by PsypherPunk** [iipc/openwayback#190]
By default, OpenWayback does not enable the`/xmlquery` endpoint for search requests. Nor do I think we have the process for enabling it documented anywhere.

The only way I can get this to work is by adding this to the `AccessPoint` configuration in `wayback.xml`:

    <property name="forceCleanQueries" value="false" />

However, I'm not sure if this is necessarily correct..? Additionally, while this works, it causes a problem in Java 8:

    The type java.util.Map$Entry cannot be resolved.

It looks like it relies on a deprecated class in that version of Java.

Finally, it looks like the query is ignoring `startdate` and `enddate` parameters; adding:

    /xmlquery?type=urlquery&startdate=20140423131055

...returns the following:

    <wayback>
      <request>
        <startdate>19910806145620</startdate>
       <numreturned>13</numreturned>
        <type>urlquery</type>
        <enddate>20141126100700</enddate>
    ...

...which doesn't match the query.

**Comment by PsypherPunk** [comment]
Regarding the first point, `/xmlquery` _is_ enabled but if the correct parameters are passed (i.e. `url` is missing) you get a raw Tomcat 404, rather than a more meaningful error message:

    HTTP/1.1 404 Not Found
    Server: Apache-Coyote/1.1
    Content-Type: text/html;charset=utf-8
    Content-Length: 1003
    Date: Wed, 11 Mar 2015 14:44:04 GMT
    
    <html><head><title>Apache Tomcat...

Still can't figure out why the `startdate` and `enddate` parameters aren't parsed though. Debugging the [code](https://github.com/iipc/openwayback/blob/master/wayback-core/src/main/java/org/archive/wayback/webapp/AccessPoint.java#L275), the `WaybackRequest` has these both set at `null`.

**Comment by anjackson** [comment]
Okay, so, because the code just pushes key-value pairs into a hash in the WaybackRequest, to debug this, I had to add a stacktrace dump to the ```put``` method. This showed that while the ```FormRequestParser``` code (called via a child class, ```ArchivalUrlFormRequestParser```, that is in the set of ```RequestParsers```) does add the timestamps to the WaybackRequest, later code then overrides those values, here:

https://github.com/iipc/openwayback/blob/6d64391226db88fbf4fc7ef44a9b2bbfbb3166da/wayback-core/src/main/java/org/archive/wayback/archivalurl/requestparser/ArchivalUrlFormRequestParser.java#L51-L52

This is old code, so this surely should have been broken a long time, but then the RequestParser system is sufficiently baroque that a change to the nature or order of the parsers could throw this out, I suppose.

Anyway, although I don't fully understand the comments in the code, it seems that the nullification is base on the assumption that you are not in ```urlquery``` or ```prefixquery``` mode, but in normal query mode. Therefore, I suggest that the fix is to *only* reset the start and end dates to null if the request matches this condition.

```java
			String replayTimestamp = wbRequest.getReplayTimestamp();
			if ((replayTimestamp == null) || replayTimestamp.length() == 0) {
				// If it's not a capture or URL query, let's call it a star
				// query:
				if (!(wbRequest.isCaptureQueryRequest() || wbRequest
						.isUrlQueryRequest())) {
					// TODO: should we clone?
					wbRequest.setStartTimestamp(null);
					wbRequest.setEndTimestamp(null);
				}
			}
```

I'll submit a pull request containing this code.

**Comment by PsypherPunk** [comment]
I've tested this and the above fix works. Unless anyone can come up with a good reason why `!(wbRequest.isCaptureQueryRequest() || wbRequest.isUrlQueryRequest())` isn't sound logic (I can't easily discern why nullifying the values is necessary), I'll merge.

**Comment by kris-sigur** [comment]
Do we want to promote this issue to the 2.2.0 milestone?

**Comment by anjackson** [comment]
I'd say yes.

**Comment by kngenie** [comment]
(I only had a quick look on the code - very likely missing something)
Intention behind the code, I guess, is to make `/query?url=URL` equivalent of `/*/URL` while `/query?url=URL&date=2014` is equivalent of `/2014*/URL`.  Without the *nullification*, `/query?url=URL` becomes `/19960101000000-20151231115959*/URL`. So the code *is* meant for capture/url query. 

For replay request, date parameter is required (not checked here, but `AccessPoint.handleReplayRedirect` failed with `NullPointerException` in my quick test - `ArchivalUrlFormRequestParser` should have set lastTimestamp).

But `PathDatePrefixQueryRequestParser` parses `/*/URL` as `/19960101000000-20151231115959*/URL` anyway. So the original code seems to be doing nothing useful but harm. Dropping lines 48--53 might be just OK and only side effect would be ugly capture search query URL when `forceCleanQueries==true` (which does not work anyway!).

There's another thing broken with `ArchivalUrlFormRequestParser`: `xmlquery` does not work with CDX Server. This is because CDX Server returns CDX in `FastCaptureSearchResult` whose `toCanonicalStringMap` always returns `null`.

**Comment by kris-sigur** [comment]
Deferred this to the next release as per discussion during the 7 May call.

**Comment by RogerMathisen** [comment]
I've looked into this briefly, and I although I do not fully understand the issue, and haven't got an overall picture of what the code does, I do have a couple of comments.

1. The suggested fix seems legit. If the request being processed is a "CaptureQueryRequest" or "UrlQueryRequest" the timestamps will be preserved, otherwise it will be nullified.

2. Regarding Kenji's comment to `xmlquery` not working with CDX-server this probably isn't optimal as we are switching to using this as our default backend from version 3. If the problem only is that `FastCaptureSearchResult.toCanonicalStringMap()` always returns null, this could be fixed by using the inherited `put()` method in all the `set...()` methods of `FastCaptureSearchResult`. (It seems like the author of `FastCaptureSearchResult` switched to using local variables for the Result parameters instead of using the original HashMap in `SearchResult`).

**Comment by johnerikhalse** [comment]
I tend to agree with @kngenie here. Just delete the lines. These lines only makes the code more difficult to understand.

**Comment by kris-sigur** [comment]
@anjackson Is this still an issue. Does PR #293 help?

**Comment by anjackson** [comment]
Well, I think the original issue is largely resolved, but the conversation has moved to xmlquery supporting the CDX Server, which should perhaps be moved into a separate issues?
