### ISSUE TITLE
current squatter robots.txt is blocking accessing to historical timestamps

### ISSUE THREAD

**Issue by whistlerbrk** [iipc/openwayback#361]
Hi, I'm trying to visit:

`http://web.archive.org/cdx/search/cdx?url=sidgames.com`

which throws:

`org.archive.util.io.RuntimeIOException: org.archive.wayback.exception.RobotAccessControlException: Blocked By Robots`

I believe, according to the source code here,  this is occurring because of the robots.txt on the current (squatted) website. The website is accessible/searchable/archived when I visit `web.archive.org/web` however. This doesn't make sense to me if my assumption is correct, why is a current robots.txt blocking historical API access?

**Comment by anjackson** [comment]
This is Internet Archive [policy](https://archive.org/about/faqs.php#14) rather than something defined in this repository.

They have been reviewing this policy and offer more information and contact details in [this blog post on the subject](https://blog.archive.org/2017/04/17/robots-txt-meant-for-search-engines-dont-work-well-for-web-archives/).

Hope that helps.

**Comment by mdubard** [comment]
@whistlerbrk were you ever able to find a work around? I'm experiencing the same issues with a couple of websites.

**Comment by anjackson** [comment]
I'm afraid all you can do is contact the Internet Archive or use Memento to look for copies in other web archives: http://timetravel.mementoweb.org/
