### ISSUE TITLE
How do you actually create an ARC file?

### ISSUE THREAD

**Issue by mtcjayne** [iipc/openwayback#375]
The documentation regularly references ARC files but I have no idea how to make them. The short term makes for unhelpful Google search results as well; I find tons of stuff on compression formats.

**Comment by ldko** [comment]
Hi @mtcjayne , 

Either ARC or WARC files can be written with the Internet Archive's web crawler [Heritrix](https://github.com/internetarchive/heritrix3).

Because the WARC file became [standard](https://www.iso.org/standard/68004.html) there are more tools for writing WARCs than ARCs (I am not sure what else writes ARC files). A couple of other tools for WARC writing are [wget](https://www.gnu.org/software/wget/manual/wget.html#index-WARC) and [warcprox](https://github.com/internetarchive/warcprox).

**Comment by mtcjayne** [comment]
Ok that's good to know. Thanks.
