### ISSUE TITLE
Resource "temporarily unavailable", log entry

### ISSUE THREAD

**Issue by oschihin** [iipc/openwayback#387]
Several warc files in openwayback are correctly indexed (I find their URLs through search), on opening the corresponding date, the message "Ressource not available" is shown. The log shows the following entry.  
```
Nov 29, 2018 3:04:58 PM org.archive.wayback.resourcestore.resourcefile.ResourceFactory getResource
WARNING: ResourceNotAvailable for /tmp/openwayback/files2/WA_88_1-1.warc Failed to find WARC MAGIC: 3�� )�+.����
```
Any hints to what may be wrong?
Thanks

**Comment by anjackson** [comment]
That's saying that `/tmp/openwayback/files2/WA_88_1-1.warc` is not a valid WARC file. It's hard to debug this kind of thing, but you could try:

- running `file /tmp/openwayback/files2/WA_88_1-1.warc` and seeing what format it appears to be
- verifying it really is the same file that was originally collected, e.g. re-transfer or re-download it
- opening it in a plain text editor and looking for clues

Hope that helps?!

**Comment by ldko** [comment]
What tool was used to create the WARCs you are using? Webrecorder recently was changed to write gzipped warc files with a `.warc` extension instead of a `.warc.gz` extension, so if you used that tool to create the WARCs, that could be causing the issue. If you have a gzipped WARC file without the `.gz` (which you should be able to tell doing the suggestion from @anjackson to run `file /tmp/openwayback/files2/WA_88_1-1.warc` and see if it says it is "gzip compressed data" or something similar), one way to solve that would be to rename the files to have a `.gz` on the end and re-index them. If you are using the default indexing setup (i. e. using `BDBCollection.xml`), you may need to shutdown OpenWayback, delete your `index` and `index-db` directories from your base directory, and restart OpenWayback to remove the references to the files before re-naming.

**Comment by oschihin** [comment]
The warc file has been created by [warcit](https://github.com/webrecorder/warcit), transforming an old collection of html files once created by [httrack](https://en.wikipedia.org/wiki/HTTrack) to warc. We have a few dozen of these collections and try ways to salvage the archives.

The warc files are created as zip `*.warc.gz`. If unpacked with `gunzip`, their `file` reads as `WA_88_1-1.warc: WARC Archive version 1.0`.

**Comment by ato** [comment]
I agree with idko that wayback finding some binary garbage instead of the WARC header sure sounds like a compression issue. The most likely causes are wayback is expecting an uncompressed record, or the file hasn't been compressed correctly per-record which may be throwing off the offsets generated by the indexer.

Maybe warcit's option to write an uncompressed warc is worth trying.

Are you finding this problem with all warc files created by warcit or just a particular one?

**Comment by ato** [comment]
By the way if you're doing httrack to warc conversion my httrack2warc tool might be worth trying too. It attempts to restore the original unmodified HTML by reading the httrack cache files. It may or may not be useful for you depending on the version of httrack and which crawl options were used and whether you kept the hts-cache directory. 

https://github.com/nla/httrack2warc/

**Comment by ldko** [comment]
Hey @oschihin, are you able to share one of the WARCs that is causing the problem?

**Comment by oschihin** [comment]
@ldko @ato thanks for your support. I cannot reconstruct the error encountered, I fumbled with lots of versions. One guess is that I did the unzipping on our solaris machine, or something went wrong in copy. Now I pack the file collections with the `--no-gzip`option of warcit, and without further touching them. I looked at httrack2warc but will not use it. Too hard to reconstruct the crawl options and files in `new.zip`of the hts-cache. After all, it seems to work now, I close here (and am happy to come back if new questions arise).
