### ISSUE TITLE
Merged WARCs

### ISSUE THREAD

**Issue by qome** [iipc/openwayback#422]
What would happen if I deleted a WARC in, for example, `files1` once it is in `index-data/merged`?

It looks like these are doubling my disk space usage so if it's safe to delete the one in `files1` after import I'd like to do that, but the two files differ when doing a binary `diff`.

**Comment by ldko** [comment]
In the default configuration given in wayback.xml, `files1` (and `files2`) are the directories from where the WARC files are read to serve content in OpenWayback. If you delete the WARC files from there, OpenWayback will no longer find the WARC files it expects, so instead of serving up archived content from those WARCs, you will end up with `Resource Not Available` when URLs in those WARCs are attempted to be accessed. The files, though named the same in `index-data/merged` are not actually the same WARC files but the index data that was created from processing the WARC file of that name. If you compare sizes of the similarly named files in `files1` vs. `index-data/merged`, the files in `index-data/merged` should be significantly smaller.

**Comment by qome** [comment]
I hadn't checked the file sizes. Thanks.
