### ISSUE TITLE
Rendering .warc does not work 

### ISSUE THREAD

**Issue by AndreSAR155** [iipc/openwayback#441]
Hello, 

I am using a software solution at work that uses OpenWayback for rendering (displaying) .warc files. However, some websites I recently archived cannot be displayed. Some problems appear to be that OpenWayback has problems rendering some fonts, images and javascript on the sites. As a result, when trying to display it, the website appears for a short instant (less than one second), then disappears. In other words, I cannot use the .warc files. 

To control if the .warc files were the problem I rendered them in another viewer, replayweb.page. The files can be displayed and interacted with just fine there. 

I have gotten several issues:

Failed to load resource: the server responded with a status of 500 ()
Failed to load resource: the server responded with a status of 404 ()
Refused to apply style from 'https://[...]' because its MIME type (text/html) is not a [...] supported stylesheet MIME type, and strict MIME checking is enabled.

Are there known solutions to these issues? I have this problem on several archived websites. It is important that I can display the .warc files using OpenWayback since this is the renderer the software we use at work utilizes. 

Looking forward to hearing about solutions,

Thank you in advance

André

**Comment by ldko** [comment]
Hi @AndreSAR155 ,

It is become increasingly common that newly developed websites don't replay cleanly in OpenWayback.

> Some problems appear to be that OpenWayback has problems rendering some fonts, images and javascript on the sites. As a result, when trying to display it, the website appears for a short instant (less than one second), then disappears. In other words, I cannot use the .warc files.

These things can happen for different reasons. OpenWayback generally works by rewriting all the URLs in the page that it is loading to also load all assets via OpenWayback and the web archive rather than trying to pull from the live web. It could be that the URLs aren't being rewritten because OpenWayback doesn't know to rewrite the type of attribute it is in, it could be that some assets aren't captured, it could be something in the JavaScript that prevents URLs being recognized and rewritten, it could be that rendering the page correctly relies on POST requests which Replayweb.page has a mechanism for handling but OpenWayback does not, it could be that code included in the archived JavaScript prevents the page from loading (or appearing for an instant than disappearing), etc.

It is hard to tell specific causes seeing only dev tools errors without knowing the URLs they are happening with and looking at code. 

> Failed to load resource: the server responded with a status of 404 ()
Refused to apply style from 'https://[...]' because its MIME type (text/html) is not a [...] supported stylesheet MIME type, and strict MIME checking is enabled.

to me indicates the css request responded with a 404 not found that was text/html, and since that is not what is expected for applying style, there is no style applied. What caused the 404 there I can't tell. It is possible we could tell more with your WARC file  or with the URL for a page you are trying to load that is having these issues and what tool you used to create the WARC, so we can try to replicate the problems. Not sure we could provide a solution at this time though if it is beyond a rewriting URL issue.

That said, knowing the issues you are seeing with replaying your WARC in OpenWayback are not specific to you and will likely continue to grow, IIPC is strongly recommending that users of OpenWayback (software that is no longer being actively worked on to fix newly arising replay issues) transition to pywb (software that is being actively developed along with Replayweb.page). To facilitate such a move, IIPC has funded a transition guide to help:

https://netpreserveblog.wordpress.com/2020/12/16/openwayback-to-pywb-transition-guide/

https://pywb.readthedocs.io/en/latest/manual/owb-transition.html

**Comment by AndreSAR155** [comment]
Hello @ldko 

Thank you very much for your reply. It is very helpful to know that IIPC recommends transitioning to pywb. 

In the case of my WARCs I believe it may, as you say, be a problem with that JavaScript either prevents URLs or prevents the archived page from loading. 

In the short term I will rely on replayweb.page to check my WARCs.

**Comment by AndreSAR155** [comment]
The main URL I archived was the following:

https://www.maastunnel.nl/#/all

I used Conifer (https://conifer.rhizome.org/) to archive it. 

If this could be used to replicate the problem and create a solution, that would be very helpful.

**Comment by ldko** [comment]
@AndreSAR155  I don't think I am seeing the same behavior you are--could be different OpenWayback versions or capture (I used pywb record mode). I am not seeing those same errors. Images and fonts and style for the site seem to be rendering ok, but one problematic thing for OpenWayback that I notice is in the https://www.maastunnel.nl/assets/javascript/body.js, there is a `window.location.replace("/#/"+t.data("source"))` that is changing the address from http:localhost:8080/wayback/20210419185242/https://www.maastunnel.nl/ to http://localhost:8080/#/all which OpenWayback doesn't do anything to prevent.

**Comment by AndreSAR155** [comment]
@ldko Thank you for trying. It is possible that it has something to do with different OpenWayback versions, or indeed the capture technology. This WARC was captured in December last year, and there have even been updates to the webrecorder products' code since then. 

The software solution I use at work has claimed they will revamp their web archiving technology in the course of this year, so for now I will rely on pywb, replayweb.page or Conifer. 

Thanks for your help
